### ISSUE TITLE
Fix bug found on tests for `cat` command in openvariant

### ISSUE THREAD

**Issue by CarlosLopezElorduy** [bbglab/openvariant#7]
When running the github action for the testing, turns out that 9 out of 12 of the tests performed on the command `cat` fail.

https://github.com/bbglab/openvariant/runs/7150358275?check_suite_focus=true

**Comment by dmartmillan** [comment]
Solved:

We realized that `listdir` function, which is located in `find_files.py` file, generates a random list of directories and files of a path. Every test that we executed it was different so it failed because the results were different.   

We have sorted it before to explore the directories and files that it throw:
```python
list_files = listdir(base_path)
list_files.sort()
```
